import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import api from "../../api/client";

export default function ExperienceCertificateList() {
  const navigate = useNavigate();
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [selectedCertificate, setSelectedCertificate] = useState(null);
  const itemsPerPage = 25;

  useEffect(() => {
    loadCertificates();
  }, []);

  const loadCertificates = async () => {
    try {
      const res = await api.get("/certificate/experience-certificates/");
      setCertificates(res?.data?.data || []);
    } catch (err) {
      console.error("Error loading certificates:", err);
    }
    setLoading(false);
  };

  const handleAddNewClick = () => {
    navigate('/experience-certificate/add');
  };

  const handleEditClick = (id) => {
    navigate(`/experience-certificate/edit/${id}`);
  };

  const handleGenerateClick = (certificate) => {
    setSelectedCertificate(certificate);
    setShowGenerateModal(true);
  };

  const handleCloseGenerate = () => {
    setShowGenerateModal(false);
    setSelectedCertificate(null);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    alert("Download functionality will be implemented with backend integration");
  };

  const handleDeleteClick = async (id) => {
    if (window.confirm("Are you sure you want to delete this record?")) {
      try {
        await api.delete(`/certificate/experience-certificates/${id}/`);
        setCertificates((prev) => prev.filter((cert) => cert.id !== id));
      } catch (err) {
        console.error("Delete error:", err);
        alert("Failed to delete certificate");
      }
    }
  };

  const filteredCertificates = certificates.filter(certificate => {
    if (!searchQuery.trim()) return true;
    const query = searchQuery.toLowerCase().trim();
    return (
      certificate.emp_name?.toLowerCase().includes(query) ||
      certificate.emp_designation?.toLowerCase().includes(query) ||
      certificate.emp_address?.toLowerCase().includes(query)
    );
  });

  const totalPages = Math.ceil(filteredCertificates.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentCertificates = filteredCertificates.slice(startIndex, endIndex);

  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery]);

  const handlePreviousPage = () => {
    setCurrentPage(prev => Math.max(prev - 1, 1));
  };

  const handleNextPage = () => {
    setCurrentPage(prev => Math.min(prev + 1, totalPages));
  };

  const handlePageClick = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  if (loading) {
    return (
      <div style={{...styles.container, display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh'}}>
        <div style={{fontSize: '18px', color: '#6b7280'}}>Loading certificate data...</div>
      </div>
    );
  }

  return (
    <div style={styles.container}>
      <div style={styles.header} className="no-print">
        <h2 style={styles.title}>Experience Certificate Management</h2>
        <div style={styles.headerActions}>
          <div style={styles.searchContainer}>
            <input
              type="text"
              placeholder="Search by name, job title, address..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={styles.searchInput}
            />
            <span style={styles.searchIcon}>🔍</span>
          </div>
          <button onClick={handleAddNewClick} style={styles.addButton}>
            + Add New
          </button>
        </div>
      </div>

      <div style={styles.tableContainer} className="no-print">
        <table style={styles.table}>
          <thead>
            <tr style={styles.tableHeaderRow}>
              <th style={styles.tableHeader}>SL NO</th>
              <th style={styles.tableHeader}>NAME</th>
              <th style={styles.tableHeader}>EMAIL</th>
              <th style={styles.tableHeader}>JOB TITLE</th>
              <th style={styles.tableHeader}>JOINING DATE</th>
              <th style={styles.tableHeader}>ISSUE DATE</th>
              <th style={styles.tableHeader}>GENERATED BY</th>
              <th style={styles.tableHeader}>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {currentCertificates.length === 0 ? (
              <tr>
                <td colSpan="9" style={styles.noResults}>
                  {searchQuery ? `No results found for "${searchQuery}"` : "No certificate records available"}
                </td>
              </tr>
            ) : (
              currentCertificates.map((certificate, index) => (
                <tr key={certificate.id} style={styles.tableRow}>
                  <td style={styles.tableCell}>{startIndex + index + 1}</td>
                  <td style={styles.tableCell}>{certificate.emp_name}</td>
                  <td style={styles.tableCell}>{certificate.emp_email || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.emp_designation}</td>
                  <td style={styles.tableCell}>{certificate.joining_date || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.issue_date || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.generated_by_name || "N/A"}</td>
                  <td style={styles.tableCell}>
                    <div style={styles.actionButtons}>
                      <button onClick={() => handleGenerateClick(certificate)} style={styles.generateBtn}>Generate</button>
                      <button onClick={() => handleEditClick(certificate.id)} style={styles.editBtn}>Edit</button>
                      <button onClick={() => handleDeleteClick(certificate.id)} style={styles.deleteBtn}>Delete</button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div style={styles.paginationContainer} className="no-print">
        <div style={styles.paginationInfo}>
          Showing {filteredCertificates.length > 0 ? startIndex + 1 : 0} to {Math.min(endIndex, filteredCertificates.length)} of {filteredCertificates.length} entries
          {searchQuery && <span style={styles.searchIndicator}> (filtered from {certificates.length} total)</span>}
        </div>
        <div style={styles.paginationButtons}>
          <button 
            onClick={handlePreviousPage} 
            disabled={currentPage === 1}
            style={{...styles.paginationBtn, ...(currentPage === 1 ? styles.paginationBtnDisabled : {})}}
          >
            Previous
          </button>
          
          <div style={styles.pageNumbers}>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map(pageNum => {
              if (
                pageNum === 1 || 
                pageNum === totalPages || 
                (pageNum >= currentPage - 1 && pageNum <= currentPage + 1)
              ) {
                return (
                  <button
                    key={pageNum}
                    onClick={() => handlePageClick(pageNum)}
                    style={{
                      ...styles.pageNumberBtn,
                      ...(pageNum === currentPage ? styles.pageNumberBtnActive : {})
                    }}
                  >
                    {pageNum}
                  </button>
                );
              } else if (pageNum === currentPage - 2 || pageNum === currentPage + 2) {
                return <span key={pageNum} style={styles.pageEllipsis}>...</span>;
              }
              return null;
            })}
          </div>

          <button 
            onClick={handleNextPage} 
            disabled={currentPage === totalPages}
            style={{...styles.paginationBtn, ...(currentPage === totalPages ? styles.paginationBtnDisabled : {})}}
          >
            Next
          </button>
        </div>
      </div>

      {/* Generate Certificate Modal */}
      {showGenerateModal && selectedCertificate && (
        <div style={styles.modalOverlay}>
          <div style={styles.generateModal}>
            <div style={styles.modalHeader} className="no-print">
              <h2 style={styles.modalTitle}>Experience Certificate</h2>
              <div style={styles.modalActions}>
                  {/* <button onClick={handlePrint} style={styles.printButton}>
                    🖨️ Print
                  </button>
                  <button onClick={handleDownload} style={styles.downloadButton}>
                    ⬇️ Download
                  </button> */}
                <button onClick={handleCloseGenerate} style={styles.closeButton}>
                  ✕
                </button>
              </div>
            </div>

            <div style={styles.certificateContainer}>
              <div style={styles.certificateBorder}>
                {/* Header with Centered Logo */}
                <div style={styles.certificateHeader}>
                  <div style={styles.logoSection}>
                    <img 
                      src="/assets/omega-logo.png" 
                      alt="Omega Logo" 
                      style={styles.headerLogo}
                      onError={(e) => {
                        e.target.style.display = 'none';
                        e.target.nextSibling.style.display = 'flex';
                      }}
                    />
                    <div style={{...styles.logoFallback, display: 'none'}}>
                      <span style={styles.omegaFallbackText}>OMEGA</span>
                    </div>
                  </div>
                </div>

                {/* Certificate Title */}
                <div style={styles.titleSection}>
                  <h1 style={styles.certificateTitle}>Experience Certificate</h1>
                  <div style={styles.titleUnderline}></div>
                </div>

                {/* Certificate Body */}
                <div style={styles.certificateBody}>
                  <p style={styles.bodyText}>
                    This is to certify that <strong style={styles.highlight}>{selectedCertificate.emp_name || "Mr./Ms. [Employee Name]"}</strong> has been employed by <strong style={styles.highlight}>OMEGA</strong> as <strong style={styles.highlight}>{selectedCertificate.emp_designation || "[Designation]"}</strong> in <strong style={styles.highlight}>[Department]</strong> during the period of{' '}
                    <strong style={styles.highlight}>
                      {selectedCertificate.joining_date 
                        ? new Date(selectedCertificate.joining_date).toLocaleDateString('en-GB', {
                            day: 'numeric',
                            month: 'long',
                            year: 'numeric'
                          })
                        : "[Start Date]"
                      }
                    </strong> to{' '}
                    <strong style={styles.highlight}>
                      {selectedCertificate.end_date 
                        ? new Date(selectedCertificate.end_date).toLocaleDateString('en-GB', {
                            day: 'numeric',
                            month: 'long',
                            year: 'numeric'
                          })
                        : "[End Date]"
                      }
                    </strong>.
                  </p>

                  <p style={styles.bodyText}>
                    His skills and qualifications proved successful with regards to task assigned to him.
                  </p>

                  <p style={styles.bodyText}>
                    This certificate was issued to him upon his own request to be submitted to whom it may concern without any liabilities towards others.
                  </p>
                </div>

                {/* Signature Section */}
                <div style={styles.signatureSection}>
                  <p style={styles.dateText}>
                    Date: {selectedCertificate.issue_date 
                      ? new Date(selectedCertificate.issue_date).toLocaleDateString('en-GB', {
                          day: 'numeric',
                          month: 'numeric',
                          year: 'numeric'
                        })
                      : new Date().toLocaleDateString('en-GB', {
                          day: 'numeric',
                          month: 'numeric',
                          year: 'numeric'
                        })
                    }
                  </p>
                  <p style={styles.signatureLabel}>Name: [Authorized Person Name]</p>
                  <p style={styles.signatureLabel}>Title: Managing Director</p>
                  <p style={styles.signatureLabel}>Signature: _______________</p>
                </div>
              </div>

              {/* Bottom Action Buttons */}
              <div style={styles.bottomActions} className="no-print">
                <button onClick={handlePrint} style={styles.bottomPrintButton}>
                  🖨️ Print Certificate
                </button>
                {/* <button onClick={handleDownload} style={styles.bottomDownloadButton}>
                  ⬇️ Download PDF
                </button> */}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  container: {
    padding: "24px",
    backgroundColor: "#f9fafb",
    minHeight: "100vh",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    flexWrap: "wrap",
    gap: "16px",
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  searchContainer: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchInput: {
    padding: "12px 40px 12px 16px",
    fontSize: "14px",
    border: "2px solid #e5e7eb",
    borderRadius: "8px",
    outline: "none",
    width: "320px",
    transition: "all 0.3s",
    fontWeight: "500",
    color: "#374151",
  },
  searchIcon: {
    position: "absolute",
    right: "14px",
    fontSize: "18px",
    pointerEvents: "none",
    color: "#9ca3af",
  },
  searchIndicator: {
    color: "#6b7280",
    fontStyle: "italic",
    fontSize: "13px",
  },
  title: {
    fontSize: "28px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
  },
  addButton: {
    padding: "12px 24px",
    fontSize: "14px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  tableContainer: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    overflow: "hidden",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHeaderRow: {
    backgroundColor: "#f3f4f6",
  },
  tableHeader: {
    padding: "12px 16px",
    textAlign: "left",
    fontSize: "12px",
    fontWeight: "600",
    color: "#6b7280",
    textTransform: "uppercase",
    borderBottom: "2px solid #e5e7eb",
  },
  tableRow: {
    borderBottom: "1px solid #e5e7eb",
    transition: "background-color 0.2s",
  },
  tableCell: {
    padding: "12px 16px",
    fontSize: "14px",
    color: "#374151",
  },
  actionButtons: {
    display: "flex",
    gap: "6px",
  },
  generateBtn: {
    padding: "6px 12px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#7c3aed",
    backgroundColor: "#ede9fe",
    border: "1px solid #ddd6fe",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  editBtn: {
    padding: "6px 12px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#3b82f6",
    backgroundColor: "#dbeafe",
    border: "1px solid #bfdbfe",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  deleteBtn: {
    padding: "6px 12px",
    fontSize: "13px",
    fontWeight: "500",
    color: "#dc2626",
    backgroundColor: "#fee2e2",
    border: "1px solid #fecaca",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "24px",
    padding: "16px 24px",
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  paginationInfo: {
    fontSize: "14px",
    color: "#6b7280",
  },
  paginationButtons: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  paginationBtn: {
    padding: "8px 16px",
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    backgroundColor: "white",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  paginationBtnDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  pageNumbers: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  pageNumberBtn: {
    padding: "8px 12px",
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
    backgroundColor: "white",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "all 0.2s",
    minWidth: "40px",
  },
  pageNumberBtnActive: {
    backgroundColor: "#3b82f6",
    color: "white",
    borderColor: "#3b82f6",
  },
  pageEllipsis: {
    padding: "8px 4px",
    color: "#9ca3af",
  },
  noResults: {
    padding: "40px",
    textAlign: "center",
    color: "#6b7280",
    fontSize: "16px",
    fontWeight: "500",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.6)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10000,
    padding: "20px",
  },
  generateModal: {
    backgroundColor: "white",
    borderRadius: "16px",
    width: "95%",
    maxWidth: "800px",
    maxHeight: "95vh",
    overflow: "auto",
    boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 30px",
    borderBottom: "2px solid #e5e7eb",
    position: "sticky",
    top: 0,
    backgroundColor: "white",
    zIndex: 10,
  },
  modalTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
  },
  modalActions: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
  },
  printButton: {
    padding: "10px 20px",
    fontSize: "14px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#059669",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  downloadButton: {
    padding: "10px 20px",
    fontSize: "14px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
  },
  closeButton: {
    fontSize: "28px",
    fontWeight: "300",
    color: "#6b7280",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
    padding: "0",
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
    transition: "all 0.2s",
  },
  certificateContainer: {
    padding: "50px 40px",
    backgroundColor: "#ffffff",
  },
  certificateBorder: {
    maxWidth: "750px",
    margin: "0 auto",
    padding: "60px 80px",
    backgroundColor: "#ffffff",
  },
  certificateHeader: {
    marginBottom: "40px",
  },
  logoSection: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "30px",
  },
  headerLogo: {
    width: "180px",
    height: "auto",
    maxHeight: "100px",
    objectFit: "contain",
  },
  logoFallback: {
    width: "180px",
    height: "100px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f3f4f6",
    border: "2px solid #d1d5db",
    borderRadius: "8px",
  },
  omegaFallbackText: {
    fontSize: "32px",
    fontWeight: "700",
    color: "#dc2626",
    fontStyle: "italic",
  },
  titleSection: {
    textAlign: "center",
    marginBottom: "50px",
  },
  certificateTitle: {
    fontSize: "22px",
    fontWeight: "400",
    color: "#4b5563",
    margin: "0 0 10px 0",
    letterSpacing: "1px",
  },
  titleUnderline: {
    width: "80px",
    height: "2px",
    backgroundColor: "#d1d5db",
    margin: "0 auto",
  },
  certificateBody: {
    marginBottom: "60px",
  },
  bodyText: {
    fontSize: "15px",
    lineHeight: "2",
    color: "#1f2937",
    marginBottom: "20px",
    textAlign: "justify",
    fontWeight: "400",
  },
  highlight: {
    color: "#000000",
    fontWeight: "600",
  },
  signatureSection: {
    marginTop: "60px",
  },
  dateText: {
    fontSize: "15px",
    color: "#1f2937",
    marginBottom: "10px",
    fontWeight: "400",
  },
  signatureLabel: {
    fontSize: "15px",
    color: "#1f2937",
    margin: "8px 0",
    fontWeight: "400",
  },
  bottomActions: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "20px",
    marginTop: "40px",
    paddingTop: "30px",
    borderTop: "2px solid #e5e7eb",
  },
  bottomPrintButton: {
    padding: "14px 32px",
    fontSize: "15px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#059669",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    transition: "all 0.3s",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  bottomDownloadButton: {
    padding: "14px 32px",
    fontSize: "15px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "10px",
    cursor: "pointer",
    transition: "all 0.3s",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
};