import React, { useState, useEffect } from "react";

// Import your API client - adjust the path as needed
import api from "../../api/client";

export default function ExperienceCertificate() {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [selectedCertificate, setSelectedCertificate] = useState(null);
  const itemsPerPage = 25;

  useEffect(() => {
    loadCertificates();
  }, []);

  const loadCertificates = async () => {
    try {
      const res = await api.get("/certificate/experience-certificates/");
      setCertificates(res?.data?.data || []);
    } catch (err) {
      console.error("Error loading certificates:", err);
    }
    setLoading(false);
  };

  const handleAddNewClick = () => {
    // Navigate to add form
    alert('Navigate to /experience-certificate/add');
  };

  const handleEditClick = (id) => {
    // Navigate to edit form
    alert(`Navigate to /experience-certificate/edit/${id}`);
  };

  const handleGenerateClick = (certificate) => {
    setSelectedCertificate(certificate);
    setShowGenerateModal(true);
  };

  const handleCloseGenerate = () => {
    setShowGenerateModal(false);
    setSelectedCertificate(null);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDeleteClick = async (id) => {
    if (window.confirm("Are you sure you want to delete this record?")) {
      try {
        await api.delete(`/certificate/experience-certificates/${id}/`);
        setCertificates((prev) => prev.filter((cert) => cert.id !== id));
        alert("Certificate deleted successfully!");
      } catch (err) {
        console.error("Delete error:", err);
        alert("Failed to delete certificate");
      }
    }
  };

  const filteredCertificates = certificates.filter(certificate => {
    if (!searchQuery.trim()) return true;
    const q = searchQuery.toLowerCase().trim();
    return (
      certificate.emp_name?.toLowerCase().includes(q) ||
      certificate.emp_designation?.toLowerCase().includes(q) ||
      certificate.emp_address?.toLowerCase().includes(q)
    );
  });

  const totalPages = Math.ceil(filteredCertificates.length / itemsPerPage);
  const startIndex = (currentPage - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  const currentCertificates = filteredCertificates.slice(startIndex, endIndex);

  useEffect(() => {
    setCurrentPage(1);
  }, [searchQuery]);

  const handlePreviousPage = () => {
    setCurrentPage(prev => Math.max(prev - 1, 1));
  };

  const handleNextPage = () => {
    setCurrentPage(prev => Math.min(prev + 1, totalPages));
  };

  const handlePageClick = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  const formatDate = (dateString) => {
    if (!dateString) return "N/A";
    const d = new Date(dateString);
    const day = d.getDate();
    const month = d.toLocaleString('en-US', { month: 'long' });
    const year = d.getFullYear();
    return `${day} ${month} ${year}`;
  };

  const formatDateShort = (dateString) => {
    if (!dateString) return new Date().toLocaleDateString('en-GB');
    return new Date(dateString).toLocaleDateString('en-GB');
  };

  if (loading) {
    return (
      <div style={{...styles.container, display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh'}}>
        <div style={{fontSize: '18px', color: '#6b7280'}}>Loading certificate data...</div>
      </div>
    );
  }

  return (
    <div style={styles.container}>
      <div style={styles.header} className="no-print">
        <h2 style={styles.title}>Experience Certificate Management</h2>
        <div style={styles.headerActions}>
          <div style={styles.searchContainer}>
            <input
              type="text"
              placeholder="Search by name, job title, address..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={styles.searchInput}
            />
            <span style={styles.searchIcon}>🔍</span>
          </div>
          <button onClick={handleAddNewClick} style={styles.addButton}>
            + Add New
          </button>
        </div>
      </div>

      <div style={styles.tableContainer} className="no-print">
        <table style={styles.table}>
          <thead>
            <tr style={styles.tableHeaderRow}>
              <th style={styles.tableHeader}>SL NO</th>
              <th style={styles.tableHeader}>NAME</th>
              <th style={styles.tableHeader}>EMAIL</th>
              <th style={styles.tableHeader}>JOB TITLE</th>
              <th style={styles.tableHeader}>JOINING DATE</th>
              <th style={styles.tableHeader}>ISSUE DATE</th>
              <th style={styles.tableHeader}>GENERATED BY</th>
              <th style={styles.tableHeader}>ACTION</th>
            </tr>
          </thead>
          <tbody>
            {currentCertificates.length === 0 ? (
              <tr>
                <td colSpan="8" style={styles.noResults}>
                  {searchQuery ? `No results found for "${searchQuery}"` : "No certificate records available"}
                </td>
              </tr>
            ) : (
              currentCertificates.map((certificate, idx) => (
                <tr key={certificate.id} style={styles.tableRow}>
                  <td style={styles.tableCell}>{startIndex + idx + 1}</td>
                  <td style={styles.tableCell}>{certificate.emp_name}</td>
                  <td style={styles.tableCell}>{certificate.emp_email || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.emp_designation}</td>
                  <td style={styles.tableCell}>{certificate.joining_date || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.issue_date || "N/A"}</td>
                  <td style={styles.tableCell}>{certificate.generated_by_name || "N/A"}</td>
                  <td style={styles.tableCell}>
                    <div style={styles.actionButtons}>
                      <button onClick={() => handleGenerateClick(certificate)} style={styles.generateBtn}>Generate</button>
                      <button onClick={() => handleEditClick(certificate.id)} style={styles.editBtn}>Edit</button>
                      <button onClick={() => handleDeleteClick(certificate.id)} style={styles.deleteBtn}>Delete</button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div style={styles.paginationContainer} className="no-print">
        <div style={styles.paginationInfo}>
          Showing {filteredCertificates.length > 0 ? startIndex + 1 : 0} to {Math.min(endIndex, filteredCertificates.length)} of {filteredCertificates.length} entries
          {searchQuery && <span style={styles.searchIndicator}> (filtered from {certificates.length} total)</span>}
        </div>
        <div style={styles.paginationButtons}>
          <button 
            onClick={handlePreviousPage} 
            disabled={currentPage === 1}
            style={{...styles.paginationBtn, ...(currentPage === 1 ? styles.paginationBtnDisabled : {})}}
          >
            Previous
          </button>
          
          <div style={styles.pageNumbers}>
            {Array.from({ length: totalPages }, (_, i) => i + 1).map(pageNum => {
              if (
                pageNum === 1 || 
                pageNum === totalPages || 
                (pageNum >= currentPage - 1 && pageNum <= currentPage + 1)
              ) {
                return (
                  <button
                    key={pageNum}
                    onClick={() => handlePageClick(pageNum)}
                    style={{
                      ...styles.pageNumberBtn,
                      ...(pageNum === currentPage ? styles.pageNumberBtnActive : {})
                    }}
                  >
                    {pageNum}
                  </button>
                );
              } else if (pageNum === currentPage - 2 || pageNum === currentPage + 2) {
                return <span key={pageNum} style={styles.pageEllipsis}>...</span>;
              }
              return null;
            })}
          </div>

          <button 
            onClick={handleNextPage} 
            disabled={currentPage === totalPages}
            style={{...styles.paginationBtn, ...(currentPage === totalPages ? styles.paginationBtnDisabled : {})}}
          >
            Next
          </button>
        </div>
      </div>

      {showGenerateModal && selectedCertificate && (
        <div style={styles.modalOverlay}>
          <div style={styles.generateModal}>
            <div style={styles.modalHeader} className="no-print">
              <h2 style={styles.modalTitle}>Experience Certificate</h2>
              <button onClick={handleCloseGenerate} style={styles.closeButton}>✕</button>
            </div>

            <div style={styles.certificateContainer}>
              <div style={styles.certificatePage}>
                {/* Header */}
                <div style={styles.certificateHeader}>
                  <div style={styles.headerLeft}>
                    <img 
                      src="/assets/omega-logo.png" 
                      alt="Omega Logo" 
                      style={styles.headerLogo}
                      onError={(e) => e.target.style.display = 'none'}
                    />
                  </div>
                  <div style={styles.headerRight}>
                    <h1 style={styles.companyName}>BASIL ENTERPRISES</h1>
                    <p style={styles.companyAddress}>
                      Omega Trade centre, Opp City Hospital<br />
                      Mavoor Road, Kozhikode,<br />
                      Malappuram Dt Kerala, India
                    </p>
                    <div style={styles.contactInfo}>
                      <span>Mob: 9961 282 899</span>
                      <span style={{marginLeft: '15px'}}>L-L: 0494 242 5702</span>
                    </div>
                    <p style={styles.gstInfo}>GSTIN : 32AEKPK8326P1Z8</p>
                  </div>
                </div>

                <div style={styles.blueLine}></div>

                {/* Ref and Date */}
                <div style={styles.refDateSection}>
                  <div>REF NO: {selectedCertificate.ref_no || "BE/HR/EXP/2025/123"}</div>
                  <div>{formatDateShort(selectedCertificate.issue_date)}</div>
                </div>

                {/* To Whom */}
                <div style={styles.toWhomSection}>
                  <p style={styles.toWhomText}>TO WHOMOSVER IT MAY CONCERN.</p>
                </div>

                {/* Watermark */}
                <div style={styles.watermark}>
                  <img 
                    src="/assets/omega-logo.png" 
                    alt="" 
                    style={styles.watermarkImage}
                    onError={(e) => e.target.style.display = 'none'}
                  />
                </div>

                {/* Content */}
                <div style={styles.mainContent}>
                  <p style={styles.employeeName}>
                    Mr. {selectedCertificate.emp_name || "EMPLOYEE NAME"}
                  </p>
                  
                  <p style={styles.bodyText}>
                    This is certify that Mr. /so Mr. A. JOHN, /so Mr. A. JOHN, was Basil Enterprises as the {selectedCertificate.emp_designation || "Business Development Manager"} as the dalyess employed with from {formatDate(selectedCertificate.joining_date)} to {selectedCertificate.emp_designation || "Manager"} from {formatDate(selectedCertificate.joining_date)}, to {formatDate(selectedCertificate.end_date)}.
                  </p>

                  <p style={styles.bodyText}>
                    During his teniure provides 12 Paidra dedication of proficiency. We wish the future endadours.
                  </p>
                </div>

                {/* Signature */}
                <div style={styles.signatureSection}>
                  <p style={styles.forCompany}>For BASIL ENTERPRISES</p>
                  <div style={{height: '50px'}}></div>
                  <p style={styles.authorizedSign}>Authorized Signistary</p>
                </div>

                {/* Footer */}
                <div style={styles.footer}>
                  <div style={styles.blueFooterLine}></div>
                  <p style={styles.footerText}>
                    www.myomega.in ~ email: hr@myomeja
                  </p>
                </div>
              </div>

              {/* Print Button */}
              <div style={styles.bottomActions} className="no-print">
                <button onClick={handlePrint} style={styles.bottomPrintButton}>
                  🖨️ Print Certificate
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

const styles = {
  container: { padding: "24px", backgroundColor: "#f9fafb", minHeight: "100vh" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px", flexWrap: "wrap", gap: "16px" },
  headerActions: { display: "flex", alignItems: "center", gap: "12px" },
  searchContainer: { position: "relative", display: "flex", alignItems: "center" },
  searchInput: { padding: "12px 40px 12px 16px", fontSize: "14px", border: "2px solid #e5e7eb", borderRadius: "8px", outline: "none", width: "320px", transition: "all 0.3s", fontWeight: "500", color: "#374151" },
  searchIcon: { position: "absolute", right: "14px", fontSize: "18px", pointerEvents: "none", color: "#9ca3af" },
  searchIndicator: { color: "#6b7280", fontStyle: "italic", fontSize: "13px" },
  title: { fontSize: "28px", fontWeight: "700", color: "#111827", margin: 0 },
  addButton: { padding: "12px 24px", fontSize: "14px", fontWeight: "600", color: "white", backgroundColor: "#3b82f6", border: "none", borderRadius: "8px", cursor: "pointer", transition: "all 0.2s", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" },
  tableContainer: { backgroundColor: "white", borderRadius: "12px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)", overflow: "hidden" },
  table: { width: "100%", borderCollapse: "collapse" },
  tableHeaderRow: { backgroundColor: "#f3f4f6" },
  tableHeader: { padding: "12px 16px", textAlign: "left", fontSize: "12px", fontWeight: "600", color: "#6b7280", textTransform: "uppercase", borderBottom: "2px solid #e5e7eb" },
  tableRow: { borderBottom: "1px solid #e5e7eb", transition: "background-color 0.2s" },
  tableCell: { padding: "12px 16px", fontSize: "14px", color: "#374151" },
  actionButtons: { display: "flex", gap: "6px" },
  generateBtn: { padding: "6px 12px", fontSize: "13px", fontWeight: "500", color: "#7c3aed", backgroundColor: "#ede9fe", border: "1px solid #ddd6fe", borderRadius: "6px", cursor: "pointer", transition: "all 0.2s" },
  editBtn: { padding: "6px 12px", fontSize: "13px", fontWeight: "500", color: "#3b82f6", backgroundColor: "#dbeafe", border: "1px solid #bfdbfe", borderRadius: "6px", cursor: "pointer", transition: "all 0.2s" },
  deleteBtn: { padding: "6px 12px", fontSize: "13px", fontWeight: "500", color: "#dc2626", backgroundColor: "#fee2e2", border: "1px solid #fecaca", borderRadius: "6px", cursor: "pointer", transition: "all 0.2s" },
  paginationContainer: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "24px", padding: "16px 24px", backgroundColor: "white", borderRadius: "12px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" },
  paginationInfo: { fontSize: "14px", color: "#6b7280" },
  paginationButtons: { display: "flex", alignItems: "center", gap: "8px" },
  paginationBtn: { padding: "8px 16px", fontSize: "14px", fontWeight: "500", color: "#374151", backgroundColor: "white", border: "1px solid #d1d5db", borderRadius: "8px", cursor: "pointer", transition: "all 0.2s" },
  paginationBtnDisabled: { opacity: 0.5, cursor: "not-allowed" },
  pageNumbers: { display: "flex", alignItems: "center", gap: "4px" },
  pageNumberBtn: { padding: "8px 12px", fontSize: "14px", fontWeight: "500", color: "#374151", backgroundColor: "white", border: "1px solid #d1d5db", borderRadius: "6px", cursor: "pointer", transition: "all 0.2s", minWidth: "40px" },
  pageNumberBtnActive: { backgroundColor: "#3b82f6", color: "white", borderColor: "#3b82f6" },
  pageEllipsis: { padding: "8px 4px", color: "#9ca3af" },
  noResults: { padding: "40px", textAlign: "center", color: "#6b7280", fontSize: "16px", fontWeight: "500" },
  modalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.6)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 10000, padding: "20px" },
  generateModal: { backgroundColor: "white", borderRadius: "16px", width: "95%", maxWidth: "210mm", maxHeight: "95vh", overflow: "auto", boxShadow: "0 25px 50px -12px rgba(0,0,0,0.25)" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "20px 30px", borderBottom: "2px solid #e5e7eb", position: "sticky", top: 0, backgroundColor: "white", zIndex: 10 },
  modalTitle: { fontSize: "22px", fontWeight: "700", color: "#111827", margin: 0 },
  closeButton: { fontSize: "28px", fontWeight: "300", color: "#6b7280", backgroundColor: "transparent", border: "none", cursor: "pointer", padding: "0", width: "36px", height: "36px", display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "8px", transition: "all 0.2s" },
  certificateContainer: { padding: "30px", backgroundColor: "#ffffff" },
  certificatePage: { width: "210mm", minHeight: "297mm", margin: "0 auto", padding: "15mm 20mm", backgroundColor: "#ffffff", boxShadow: "0 0 10px rgba(0,0,0,0.1)", position: "relative", fontFamily: "Arial, sans-serif" },
  certificateHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "10px", borderBottom: "1px solid #ddd", paddingBottom: "10px" },
  headerLeft: { flex: "0 0 auto" },
  headerLogo: { width: "80px", height: "auto", objectFit: "contain" },
  headerRight: { flex: 1, textAlign: "right", paddingLeft: "20px" },
  companyName: { fontSize: "18px", fontWeight: "bold", color: "#000", margin: "0 0 8px 0", letterSpacing: "1px" },
  companyAddress: { fontSize: "10px", color: "#333", lineHeight: "1.4", margin: "0 0 6px 0" },
  contactInfo: { fontSize: "10px", color: "#333", marginBottom: "4px" },
  gstInfo: { fontSize: "9px", color: "#333", margin: 0 },
  blueLine: { height: "3px", backgroundColor: "#00bcd4", marginBottom: "25px" },
  refDateSection: { display: "flex", justifyContent: "space-between", marginBottom: "30px", fontSize: "11px", color: "#000", fontWeight: "500" },
  toWhomSection: { marginBottom: "40px" },
  toWhomText: { fontSize: "12px", fontWeight: "600", color: "#000", margin: 0, letterSpacing: "0.5px" },
  watermark: { position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", opacity: 0.05, pointerEvents: "none", zIndex: 0 },
  watermarkImage: { width: "400px", height: "auto" },
  mainContent: { position: "relative", zIndex: 1, marginBottom: "60px", minHeight: "200px" },
  employeeName: { fontSize: "12px", fontWeight: "600", color: "#000", marginBottom: "20px" },
  bodyText: { fontSize: "11px", lineHeight: "1.8", color: "#000", textAlign: "justify", marginBottom: "15px" },
  signatureSection: { marginTop: "80px", position: "relative", zIndex: 1 },
  forCompany: { fontSize: "11px", fontWeight: "600", color: "#000", marginBottom: "10px" },
  authorizedSign: { fontSize: "11px", fontWeight: "500", color: "#000" },
  footer: { position: "absolute", bottom: "15mm", left: "20mm", right: "20mm" },
  blueFooterLine: { height: "3px", backgroundColor: "#00bcd4", marginBottom: "8px" },
  footerText: { fontSize: "10px", color: "#000", textAlign: "center", margin: 0 },
  bottomActions: { display: "flex", justifyContent: "center", alignItems: "center", gap: "20px", marginTop: "30px", paddingTop: "20px", borderTop: "2px solid #e5e7eb" },
  bottomPrintButton: { padding: "14px 32px", fontSize: "15px", fontWeight: "600", color: "white", backgroundColor: "#059669", border: "none", borderRadius: "10px", cursor: "pointer", transition: "all 0.3s", boxShadow: "0 4px 6px rgba(0,0,0,0.1)", display: "flex", alignItems: "center", gap: "8px" },
};