import React, { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";

export default function OfferLetterForm() {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEdit = Boolean(id);

  const [formData, setFormData] = useState({
    name: "",
    jobTitle: "",
    phoneNumber: "",
    place: "",
    generatedBy: "",
    status: "Willing",
    generateDetails: "",
    cvAttachmentUrl: "",
    cvFileName: "",
    offerLetterUrl: "",
    offerLetterFileName: "",
  });

  useEffect(() => {
    if (isEdit) {
      const storedData = JSON.parse(localStorage.getItem("offer-letter-management-data")) || [];
      const record = storedData.find((r) => r.id === parseInt(id));
      if (record) setFormData(record);
    }
  }, [id, isEdit]);

  const handleChange = (e) => {
    setFormData((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const storedData = JSON.parse(localStorage.getItem("offer-letter-management-data")) || [];

    if (isEdit) {
      const updated = storedData.map((item) =>
        item.id === parseInt(id) ? { ...item, ...formData } : item
      );
      localStorage.setItem("offer-letter-management-data", JSON.stringify(updated));
      alert("Offer letter updated successfully!");
    } else {
      const newRecord = {
        ...formData,
        id: Date.now(),
        createdUser: "myomega@gmail.com",
        createdDate: new Date().toLocaleString(),
      };
      localStorage.setItem(
        "offer-letter-management-data",
        JSON.stringify([...storedData, newRecord])
      );
      alert("Offer letter added successfully!");
    }

    navigate("/offer-letter");
  };

  const handleCancel = () => navigate("/offer-letter");

  return (
    <div style={styles.container}>
      <div style={styles.formCard}>
        <div style={styles.header}>
          <h2 style={styles.title}>{isEdit ? "Edit Offer Letter" : "Add New Offer Letter"}</h2>
          <button onClick={handleCancel} style={styles.backButton}>← Back to List</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div style={styles.formGrid}>
            <div style={styles.formGroup}>
              <label style={styles.label}>Name *</label>
              <input
                style={styles.input}
                name="name"
                value={formData.name}
                onChange={handleChange}
                placeholder="Enter full name"
                required
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Job Title *</label>
              <input
                style={styles.input}
                name="jobTitle"
                value={formData.jobTitle}
                onChange={handleChange}
                placeholder="Enter job title"
                required
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Phone Number</label>
              <input
                style={styles.input}
                name="phoneNumber"
                value={formData.phoneNumber}
                onChange={handleChange}
                placeholder="Enter phone number"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Location</label>
              <input
                style={styles.input}
                name="place"
                value={formData.place}
                onChange={handleChange}
                placeholder="Enter location"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Generated By</label>
              <input
                style={styles.input}
                name="generatedBy"
                value={formData.generatedBy}
                onChange={handleChange}
                placeholder="Enter generated by"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Status</label>
              <select
                style={styles.input}
                name="status"
                value={formData.status}
                onChange={handleChange}
              >
                <option value="Willing">Willing</option>
                <option value="Not Willing">Not Willing</option>
              </select>
            </div>

            <div style={{ ...styles.formGroup, gridColumn: "1 / -1" }}>
              <label style={styles.label}>Generate Details</label>
              <textarea
                style={styles.textarea}
                name="generateDetails"
                value={formData.generateDetails}
                onChange={handleChange}
                rows="4"
                placeholder="Enter generation details"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>CV URL</label>
              <input
                style={styles.input}
                name="cvAttachmentUrl"
                value={formData.cvAttachmentUrl}
                onChange={handleChange}
                placeholder="Paste CV link or file URL"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>CV File Name</label>
              <input
                style={styles.input}
                name="cvFileName"
                value={formData.cvFileName}
                onChange={handleChange}
                placeholder="Enter CV file name"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Offer Letter URL</label>
              <input
                style={styles.input}
                name="offerLetterUrl"
                value={formData.offerLetterUrl}
                onChange={handleChange}
                placeholder="Paste offer letter URL"
              />
            </div>

            <div style={styles.formGroup}>
              <label style={styles.label}>Offer Letter File Name</label>
              <input
                style={styles.input}
                name="offerLetterFileName"
                value={formData.offerLetterFileName}
                onChange={handleChange}
                placeholder="Enter offer letter file name"
              />
            </div>
          </div>

          <div style={styles.formFooter}>
            <button type="button" onClick={handleCancel} style={styles.cancelBtn}>
              Cancel
            </button>
            <button type="submit" style={styles.submitBtn}>
              {isEdit ? "Update Offer Letter" : "Submit Offer Letter"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

const styles = {
  container: {
    padding: "24px",
    backgroundColor: "#f9fafb",
    minHeight: "100vh",
  },
  formCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "32px",
    maxWidth: "1000px",
    margin: "0 auto",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    paddingBottom: "20px",
    borderBottom: "2px solid #e5e7eb",
  },
  title: {
    fontSize: "28px",
    fontWeight: "700",
    color: "#111827",
    margin: 0,
  },
  backButton: {
    padding: "10px 20px",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    backgroundColor: "white",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
    marginBottom: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
  },
  input: {
    padding: "12px 16px",
    fontSize: "14px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    outline: "none",
    transition: "all 0.2s",
  },
  textarea: {
    padding: "12px 16px",
    fontSize: "14px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    outline: "none",
    resize: "vertical",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },
  formFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "12px",
    marginTop: "32px",
    paddingTop: "24px",
    borderTop: "1px solid #e5e7eb",
  },
  cancelBtn: {
    padding: "12px 24px",
    fontSize: "14px",
    fontWeight: "600",
    color: "#374151",
    backgroundColor: "white",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  submitBtn: {
    padding: "12px 24px",
    fontSize: "14px",
    fontWeight: "600",
    color: "white",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
};
