// src/components/TargetManagement/CallTargetAssign.jsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import api from "../../api/client";

const CallTargetAssign = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [employees, setEmployees] = useState([]);

  const [formData, setFormData] = useState({
    employee: '',
    start_date: '',
    end_date: '',
    notes: '',
    is_active: true,
    auto_create_daily_targets: true,
    daily_targets: []
  });

  useEffect(() => {
    fetchEmployees();
  }, []);

  // Generate daily targets when dates change
  useEffect(() => {
    if (formData.start_date && formData.end_date && formData.auto_create_daily_targets) {
      generateDailyTargets();
    }
  }, [formData.start_date, formData.end_date]);

  const fetchEmployees = async () => {
    try {
      const response = await api.get('/employee-management/employees/');
      setEmployees(response.data.results || response.data);
    } catch (error) {
      toast.error('Failed to load employees');
      console.error(error);
    }
  };

  // Helper function to get employee display name
  const getEmployeeDisplayName = (emp) => {
    return emp.full_name || emp.name || `${emp.first_name || ''} ${emp.last_name || ''}`.trim() || 'Unknown';
  };

  const generateDailyTargets = () => {
    const start = new Date(formData.start_date);
    const end = new Date(formData.end_date);
    const targets = [];

    let current = new Date(start);
    while (current <= end) {
      // Default target calls based on day of week (lower on weekends)
      const dayOfWeek = current.getDay();
      const defaultCalls = dayOfWeek === 0 || dayOfWeek === 6 ? 20 : 30;

      targets.push({
        target_date: current.toISOString().split('T')[0],
        target_calls: defaultCalls,
        achieved_calls: 0,
        productive_calls: 0,
        order_received: 0,
        order_amount: 0,
        remarks: ''
      });
      current.setDate(current.getDate() + 1);
    }

    setFormData(prev => ({ ...prev, daily_targets: targets }));
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const updateDailyTarget = (index, field, value) => {
    const updated = [...formData.daily_targets];
    updated[index][field] = value;
    setFormData(prev => ({ ...prev, daily_targets: updated }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate dates
    if (formData.start_date && formData.end_date) {
      if (new Date(formData.end_date) < new Date(formData.start_date)) {
        toast.error('End date must be after start date');
        return;
      }
    }

    setLoading(true);

    try {
      // Prepare data for submission
      // NOTE: We don't send daily_targets because the backend auto-generates them
      // based on start_date and end_date (see CallTargetPeriodSerializer.create)
      const submitData = {
        employee: parseInt(formData.employee),
        start_date: formData.start_date,
        end_date: formData.end_date,
        notes: formData.notes || '',
        is_active: formData.is_active
        // daily_targets will be auto-generated by backend
      };
      
      console.log('Submitting call target data:', submitData);
      const response = await api.post('/target-management/call-targets/', submitData);
      console.log('Success response:', response.data);
      toast.success('Call target assigned successfully! Daily targets have been auto-generated.');
      navigate('/target/call/list');
    } catch (error) {
      console.log('Full error response:', error.response?.data);
      console.log('Error status:', error.response?.status);
      
      // Handle validation errors
      if (error.response?.data) {
        const errorData = error.response.data;
        
        // If there are field-specific errors, show them
        if (typeof errorData === 'object' && !errorData.detail && !errorData.message) {
          const errorMessages = [];
          Object.keys(errorData).forEach(field => {
            const fieldErrors = Array.isArray(errorData[field]) 
              ? errorData[field] 
              : [errorData[field]];
            fieldErrors.forEach(err => {
              errorMessages.push(`${field}: ${err}`);
            });
          });
          toast.error(errorMessages.join('\n') || 'Validation error');
        } else {
          // Single error message
          const errorMsg = errorData.detail || 
                           errorData.message ||
                           'Failed to assign call target';
          toast.error(errorMsg);
        }
      } else {
        toast.error('Failed to assign call target');
      }
      
      console.error('Submit error:', error);
    } finally {
      setLoading(false);
    }
  };

  // Helper function to get Monday of current week
  const getMondayOfWeek = (date) => {
    const d = new Date(date);
    const day = d.getDay();
    const diff = d.getDate() - day + (day === 0 ? -6 : 1);
    return new Date(d.setDate(diff));
  };

  // Helper function to get Sunday of current week
  const getSundayOfWeek = (date) => {
    const monday = getMondayOfWeek(date);
    const sunday = new Date(monday);
    sunday.setDate(monday.getDate() + 6);
    return sunday;
  };

  // Preset week selection
  const selectCurrentWeek = () => {
    const monday = getMondayOfWeek(new Date());
    const sunday = getSundayOfWeek(new Date());
    
    setFormData(prev => ({
      ...prev,
      start_date: monday.toISOString().split('T')[0],
      end_date: sunday.toISOString().split('T')[0]
    }));
  };

  const selectNextWeek = () => {
    const nextMonday = getMondayOfWeek(new Date());
    nextMonday.setDate(nextMonday.getDate() + 7);
    const nextSunday = new Date(nextMonday);
    nextSunday.setDate(nextMonday.getDate() + 6);
    
    setFormData(prev => ({
      ...prev,
      start_date: nextMonday.toISOString().split('T')[0],
      end_date: nextSunday.toISOString().split('T')[0]
    }));
  };

  // Format date to display day name
  const getDayName = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { weekday: 'long' });
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  return (
    <div className="container-fluid py-4">
      <div className="row">
        <div className="col-12">
          <div className="card">
            <div className="card-header pb-0">
              <div className="d-flex align-items-center justify-content-between">
                <h6>Assign Call Target</h6>
                <button
                  className="btn btn-sm btn-outline-secondary"
                  onClick={() => navigate('/target/call/list')}
                >
                  ← Back to List
                </button>
              </div>
            </div>

            <div className="card-body">
              <form onSubmit={handleSubmit}>
                {/* Employee Selection */}
                <div className="row">
                  <div className="col-md-12 mb-3">
                    <label className="form-label">Employee *</label>
                    <select
                      name="employee"
                      className="form-select"
                      value={formData.employee}
                      onChange={handleInputChange}
                      required
                    >
                      <option value="">Select Employee</option>
                      {employees.map(emp => (
                        <option key={emp.id} value={emp.id}>
                          {emp.employee_id} - {getEmployeeDisplayName(emp)}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                {/* Week Selection with Calendar */}
                <div className="mb-3">
                  <label className="form-label">Select Target Period *</label>
                  
                  {/* Quick Week Buttons */}
                  <div className="mb-3">
                    <div className="btn-group" role="group">
                      <button
                        type="button"
                        className="btn btn-outline-primary btn-sm"
                        onClick={selectCurrentWeek}
                      >
                        Current Week
                      </button>
                      <button
                        type="button"
                        className="btn btn-outline-primary btn-sm"
                        onClick={selectNextWeek}
                      >
                        Next Week
                      </button>
                    </div>
                  </div>

                  {/* Date Range Selection */}
                  <div className="row">
                    <div className="col-md-6 mb-3">
                      <label className="form-label">Start Date *</label>
                      <input
                        type="date"
                        name="start_date"
                        className="form-control"
                        value={formData.start_date}
                        onChange={handleInputChange}
                        required
                      />
                      {formData.start_date && (
                        <small className="text-muted">
                          {new Date(formData.start_date).toLocaleDateString('en-US', { 
                            weekday: 'long', 
                            year: 'numeric', 
                            month: 'long', 
                            day: 'numeric' 
                          })}
                        </small>
                      )}
                    </div>

                    <div className="col-md-6 mb-3">
                      <label className="form-label">End Date *</label>
                      <input
                        type="date"
                        name="end_date"
                        className="form-control"
                        value={formData.end_date}
                        onChange={handleInputChange}
                        required
                      />
                      {formData.end_date && (
                        <small className="text-muted">
                          {new Date(formData.end_date).toLocaleDateString('en-US', { 
                            weekday: 'long', 
                            year: 'numeric', 
                            month: 'long', 
                            day: 'numeric' 
                          })}
                        </small>
                      )}
                    </div>
                  </div>

                  {/* Period Summary */}
                  {formData.start_date && formData.end_date && (
                    <div className="alert alert-info">
                      <strong>Period Summary:</strong> {' '}
                      {formatDate(formData.start_date)}
                      {' - '}
                      {formatDate(formData.end_date)}
                      {' ('}
                      {Math.ceil((new Date(formData.end_date) - new Date(formData.start_date)) / (1000 * 60 * 60 * 24)) + 1} days
                      {')'}
                    </div>
                  )}
                </div>

                {/* Auto-create Daily Targets */}
                <div className="form-check mb-3">
                  <input
                    type="checkbox"
                    name="auto_create_daily_targets"
                    className="form-check-input"
                    checked={formData.auto_create_daily_targets}
                    onChange={handleInputChange}
                    id="autoCreateCheck"
                  />
                  <label className="form-check-label" htmlFor="autoCreateCheck">
                    Auto-generate daily targets for the selected period
                  </label>
                </div>

                {/* Daily Targets Table */}
                {formData.daily_targets.length > 0 && (
                  <div className="mb-3">
                    <h6 className="mb-3">Daily Call Targets</h6>
                    <div className="table-responsive">
                      <table className="table table-bordered table-hover">
                        <thead className="table-light">
                          <tr>
                            <th style={{ width: '150px' }}>Date</th>
                            <th>Target Calls *</th>
                            <th>Achieved Calls</th>
                            <th>Productive Calls</th>
                            <th>Orders Received</th>
                            <th>Order Amount</th>
                            <th>Remarks</th>
                          </tr>
                        </thead>
                        <tbody>
                          {formData.daily_targets.map((target, index) => (
                            <tr key={index}>
                              <td>
                                <strong>{getDayName(target.target_date)}</strong>
                                <br />
                                <small className="text-muted">{formatDate(target.target_date)}</small>
                              </td>
                              <td>
                                <input
                                  type="number"
                                  className="form-control form-control-sm"
                                  value={target.target_calls}
                                  onChange={(e) => updateDailyTarget(index, 'target_calls', e.target.value)}
                                  min="0"
                                  required
                                />
                              </td>
                              <td>
                                <input
                                  type="number"
                                  className="form-control form-control-sm"
                                  value={target.achieved_calls}
                                  onChange={(e) => updateDailyTarget(index, 'achieved_calls', e.target.value)}
                                  min="0"
                                />
                              </td>
                              <td>
                                <input
                                  type="number"
                                  className="form-control form-control-sm"
                                  value={target.productive_calls}
                                  onChange={(e) => updateDailyTarget(index, 'productive_calls', e.target.value)}
                                  min="0"
                                />
                              </td>
                              <td>
                                <input
                                  type="number"
                                  className="form-control form-control-sm"
                                  value={target.order_received}
                                  onChange={(e) => updateDailyTarget(index, 'order_received', e.target.value)}
                                  min="0"
                                />
                              </td>
                              <td>
                                <input
                                  type="number"
                                  className="form-control form-control-sm"
                                  value={target.order_amount}
                                  onChange={(e) => updateDailyTarget(index, 'order_amount', e.target.value)}
                                  step="0.01"
                                  min="0"
                                />
                              </td>
                              <td>
                                <input
                                  type="text"
                                  className="form-control form-control-sm"
                                  value={target.remarks}
                                  onChange={(e) => updateDailyTarget(index, 'remarks', e.target.value)}
                                  placeholder="Notes"
                                />
                              </td>
                            </tr>
                          ))}
                        </tbody>
                        <tfoot className="table-light">
                          <tr>
                            <td><strong>Total</strong></td>
                            <td>
                              <strong>
                                {formData.daily_targets.reduce((sum, t) => sum + Number(t.target_calls || 0), 0)}
                              </strong>
                            </td>
                            <td>
                              <strong>
                                {formData.daily_targets.reduce((sum, t) => sum + Number(t.achieved_calls || 0), 0)}
                              </strong>
                            </td>
                            <td>
                              <strong>
                                {formData.daily_targets.reduce((sum, t) => sum + Number(t.productive_calls || 0), 0)}
                              </strong>
                            </td>
                            <td>
                              <strong>
                                {formData.daily_targets.reduce((sum, t) => sum + Number(t.order_received || 0), 0)}
                              </strong>
                            </td>
                            <td>
                              <strong>
                                ₹{formData.daily_targets.reduce((sum, t) => sum + Number(t.order_amount || 0), 0).toFixed(2)}
                              </strong>
                            </td>
                            <td></td>
                          </tr>
                        </tfoot>
                      </table>
                    </div>
                  </div>
                )}

                {/* General Notes */}
                <div className="mb-3">
                  <label className="form-label">General Notes</label>
                  <textarea
                    name="notes"
                    className="form-control"
                    value={formData.notes}
                    onChange={handleInputChange}
                    rows="3"
                    placeholder="Optional notes about this call target assignment"
                  />
                </div>

                {/* Active Status */}
                <div className="form-check mb-3">
                  <input
                    type="checkbox"
                    name="is_active"
                    className="form-check-input"
                    checked={formData.is_active}
                    onChange={handleInputChange}
                    id="isActiveCheck"
                  />
                  <label className="form-check-label" htmlFor="isActiveCheck">
                    Active
                  </label>
                </div>

                {/* Submit Button */}
                <div className="d-flex justify-content-end gap-2">
                  <button
                    type="button"
                    className="btn btn-outline-secondary"
                    onClick={() => navigate('/target/call/list')}
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="btn btn-primary"
                    disabled={loading}
                  >
                    {loading ? 'Assigning...' : 'Assign Call Target'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CallTargetAssign;